/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Teampage
 * Uoslife Teampage API Swagger
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  ArticleDetailResponse,
  CommentCreateRequest,
  CommentResponse,
  CommentUpdateRequest,
  CreateArticleRequest,
  Me200,
  PageArticleListItem,
  SearchArticlesParams,
  UpdateArticleRequest,
} from './teampage.schemas';

export type searchArticlesResponse200 = {
  data: PageArticleListItem;
  status: 200;
};

export type searchArticlesResponseComposite = searchArticlesResponse200;

export type searchArticlesResponse = searchArticlesResponseComposite & {
  headers: Headers;
};

export const getSearchArticlesUrl = (params: SearchArticlesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(
        key,
        value === null
          ? 'null'
          : value instanceof Date
            ? value.toISOString()
            : value.toString(),
      );
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://apis.uoslife.team/articles?${stringifiedParams}`
    : `https://apis.uoslife.team/articles`;
};

export const searchArticles = async (
  params: SearchArticlesParams,
  options?: RequestInit,
): Promise<searchArticlesResponse> => {
  const res = await fetch(getSearchArticlesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: searchArticlesResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as searchArticlesResponse;
};

export const getSearchArticlesQueryKey = (params?: SearchArticlesParams) => {
  return [
    `https://apis.uoslife.team/articles`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSearchArticlesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchArticlesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchArticles>>> = ({
    signal,
  }) => searchArticles(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchArticles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchArticlesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchArticles>>
>;
export type SearchArticlesQueryError = unknown;

export function useSearchArticles<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchArticles>>,
          TError,
          Awaited<ReturnType<typeof searchArticles>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchArticles<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchArticles>>,
          TError,
          Awaited<ReturnType<typeof searchArticles>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchArticles<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchArticles<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchArticlesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchSearchArticlesQuery = async <
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchArticles>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getSearchArticlesQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getSearchArticlesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchArticles>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchArticlesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchArticles>>> = ({
    signal,
  }) => searchArticles(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof searchArticles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchArticlesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchArticles>>
>;
export type SearchArticlesSuspenseQueryError = unknown;

export function useSearchArticlesSuspense<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchArticles>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchArticlesSuspense<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchArticles>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchArticlesSuspense<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchArticles>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchArticlesSuspense<
  TData = Awaited<ReturnType<typeof searchArticles>>,
  TError = unknown,
>(
  params: SearchArticlesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchArticles>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchArticlesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type createArticleResponse200 = {
  data: ArticleDetailResponse;
  status: 200;
};

export type createArticleResponseComposite = createArticleResponse200;

export type createArticleResponse = createArticleResponseComposite & {
  headers: Headers;
};

export const getCreateArticleUrl = () => {
  return `https://apis.uoslife.team/articles`;
};

export const createArticle = async (
  createArticleRequest: CreateArticleRequest,
  options?: RequestInit,
): Promise<createArticleResponse> => {
  const res = await fetch(getCreateArticleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createArticleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createArticleResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createArticleResponse;
};

export const getCreateArticleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createArticle>>,
    TError,
    { data: CreateArticleRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createArticle>>,
  TError,
  { data: CreateArticleRequest },
  TContext
> => {
  const mutationKey = ['createArticle'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createArticle>>,
    { data: CreateArticleRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createArticle(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateArticleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createArticle>>
>;
export type CreateArticleMutationBody = CreateArticleRequest;
export type CreateArticleMutationError = unknown;

export const useCreateArticle = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createArticle>>,
      TError,
      { data: CreateArticleRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createArticle>>,
  TError,
  { data: CreateArticleRequest },
  TContext
> => {
  const mutationOptions = getCreateArticleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type createCommentResponse200 = {
  data: CommentResponse;
  status: 200;
};

export type createCommentResponseComposite = createCommentResponse200;

export type createCommentResponse = createCommentResponseComposite & {
  headers: Headers;
};

export const getCreateCommentUrl = (articleId: number) => {
  return `https://apis.uoslife.team/articles/${articleId}/comments`;
};

export const createComment = async (
  articleId: number,
  commentCreateRequest: CommentCreateRequest,
  options?: RequestInit,
): Promise<createCommentResponse> => {
  const res = await fetch(getCreateCommentUrl(articleId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(commentCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createCommentResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createCommentResponse;
};

export const getCreateCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    { articleId: number; data: CommentCreateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { articleId: number; data: CommentCreateRequest },
  TContext
> => {
  const mutationKey = ['createComment'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComment>>,
    { articleId: number; data: CommentCreateRequest }
  > = (props) => {
    const { articleId, data } = props ?? {};

    return createComment(articleId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComment>>
>;
export type CreateCommentMutationBody = CommentCreateRequest;
export type CreateCommentMutationError = unknown;

export const useCreateComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createComment>>,
      TError,
      { articleId: number; data: CommentCreateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { articleId: number; data: CommentCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type findArticleResponse200 = {
  data: ArticleDetailResponse;
  status: 200;
};

export type findArticleResponseComposite = findArticleResponse200;

export type findArticleResponse = findArticleResponseComposite & {
  headers: Headers;
};

export const getFindArticleUrl = (articleId: number) => {
  return `https://apis.uoslife.team/articles/${articleId}`;
};

export const findArticle = async (
  articleId: number,
  options?: RequestInit,
): Promise<findArticleResponse> => {
  const res = await fetch(getFindArticleUrl(articleId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: findArticleResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as findArticleResponse;
};

export const getFindArticleQueryKey = (articleId?: number) => {
  return [`https://apis.uoslife.team/articles/${articleId}`] as const;
};

export const getFindArticleQueryOptions = <
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindArticleQueryKey(articleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findArticle>>> = ({
    signal,
  }) => findArticle(articleId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!articleId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof findArticle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindArticleQueryResult = NonNullable<
  Awaited<ReturnType<typeof findArticle>>
>;
export type FindArticleQueryError = unknown;

export function useFindArticle<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findArticle>>,
          TError,
          Awaited<ReturnType<typeof findArticle>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindArticle<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findArticle>>,
          TError,
          Awaited<ReturnType<typeof findArticle>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindArticle<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindArticle<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindArticleQueryOptions(articleId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchFindArticleQuery = async <
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  articleId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findArticle>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getFindArticleQueryOptions(articleId, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getFindArticleSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findArticle>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindArticleQueryKey(articleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findArticle>>> = ({
    signal,
  }) => findArticle(articleId, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findArticle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindArticleSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findArticle>>
>;
export type FindArticleSuspenseQueryError = unknown;

export function useFindArticleSuspense<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findArticle>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindArticleSuspense<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findArticle>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindArticleSuspense<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findArticle>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindArticleSuspense<
  TData = Awaited<ReturnType<typeof findArticle>>,
  TError = unknown,
>(
  articleId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findArticle>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindArticleSuspenseQueryOptions(articleId, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type updateArticleResponse200 = {
  data: ArticleDetailResponse;
  status: 200;
};

export type updateArticleResponseComposite = updateArticleResponse200;

export type updateArticleResponse = updateArticleResponseComposite & {
  headers: Headers;
};

export const getUpdateArticleUrl = (articleId: number) => {
  return `https://apis.uoslife.team/articles/${articleId}`;
};

export const updateArticle = async (
  articleId: number,
  updateArticleRequest: UpdateArticleRequest,
  options?: RequestInit,
): Promise<updateArticleResponse> => {
  const res = await fetch(getUpdateArticleUrl(articleId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateArticleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateArticleResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateArticleResponse;
};

export const getUpdateArticleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateArticle>>,
    TError,
    { articleId: number; data: UpdateArticleRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateArticle>>,
  TError,
  { articleId: number; data: UpdateArticleRequest },
  TContext
> => {
  const mutationKey = ['updateArticle'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateArticle>>,
    { articleId: number; data: UpdateArticleRequest }
  > = (props) => {
    const { articleId, data } = props ?? {};

    return updateArticle(articleId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateArticleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateArticle>>
>;
export type UpdateArticleMutationBody = UpdateArticleRequest;
export type UpdateArticleMutationError = unknown;

export const useUpdateArticle = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateArticle>>,
      TError,
      { articleId: number; data: UpdateArticleRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateArticle>>,
  TError,
  { articleId: number; data: UpdateArticleRequest },
  TContext
> => {
  const mutationOptions = getUpdateArticleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type deleteCommentResponse200 = {
  data: null;
  status: 200;
};

export type deleteCommentResponseComposite = deleteCommentResponse200;

export type deleteCommentResponse = deleteCommentResponseComposite & {
  headers: Headers;
};

export const getDeleteCommentUrl = (articleId: number, commentId: number) => {
  return `https://apis.uoslife.team/articles/${articleId}/comments/${commentId}`;
};

export const deleteComment = async (
  articleId: number,
  commentId: number,
  options?: RequestInit,
): Promise<deleteCommentResponse> => {
  const res = await fetch(getDeleteCommentUrl(articleId, commentId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteCommentResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteCommentResponse;
};

export const getDeleteCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    { articleId: number; commentId: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { articleId: number; commentId: number },
  TContext
> => {
  const mutationKey = ['deleteComment'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    { articleId: number; commentId: number }
  > = (props) => {
    const { articleId, commentId } = props ?? {};

    return deleteComment(articleId, commentId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>;

export type DeleteCommentMutationError = unknown;

export const useDeleteComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      { articleId: number; commentId: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { articleId: number; commentId: number },
  TContext
> => {
  const mutationOptions = getDeleteCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type updateCommentResponse200 = {
  data: CommentResponse;
  status: 200;
};

export type updateCommentResponseComposite = updateCommentResponse200;

export type updateCommentResponse = updateCommentResponseComposite & {
  headers: Headers;
};

export const getUpdateCommentUrl = (articleId: number, commentId: number) => {
  return `https://apis.uoslife.team/articles/${articleId}/comments/${commentId}`;
};

export const updateComment = async (
  articleId: number,
  commentId: number,
  commentUpdateRequest: CommentUpdateRequest,
  options?: RequestInit,
): Promise<updateCommentResponse> => {
  const res = await fetch(getUpdateCommentUrl(articleId, commentId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(commentUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateCommentResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateCommentResponse;
};

export const getUpdateCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComment>>,
    TError,
    { articleId: number; commentId: number; data: CommentUpdateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { articleId: number; commentId: number; data: CommentUpdateRequest },
  TContext
> => {
  const mutationKey = ['updateComment'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComment>>,
    { articleId: number; commentId: number; data: CommentUpdateRequest }
  > = (props) => {
    const { articleId, commentId, data } = props ?? {};

    return updateComment(articleId, commentId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComment>>
>;
export type UpdateCommentMutationBody = CommentUpdateRequest;
export type UpdateCommentMutationError = unknown;

export const useUpdateComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComment>>,
      TError,
      { articleId: number; commentId: number; data: CommentUpdateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { articleId: number; commentId: number; data: CommentUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type meResponse200 = {
  data: Me200;
  status: 200;
};

export type meResponseComposite = meResponse200;

export type meResponse = meResponseComposite & {
  headers: Headers;
};

export const getMeUrl = () => {
  return `https://apis.uoslife.team/auth/me`;
};

export const me = async (options?: RequestInit): Promise<meResponse> => {
  const res = await fetch(getMeUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: meResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as meResponse;
};

export const getMeQueryKey = () => {
  return [`https://apis.uoslife.team/auth/me`] as const;
};

export const getMeQueryOptions = <
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) =>
    me({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof me>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeQueryError = unknown;

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = unknown>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = unknown>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = unknown>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = unknown>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchMeQuery = async <
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getMeQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) =>
    me({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof me>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeSuspenseQueryError = unknown;

export function useMeSuspense<
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMeSuspense<
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMeSuspense<
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMeSuspense<
  TData = Awaited<ReturnType<typeof me>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
